# config\packages\nelmio_api_doc.yaml

nelmio_api_doc:
    documentation:
        info:
            title: BileMo API
            description: Une API qui vous permet de partager un catalogue de téléphones dernier cri avec vos clients.
            version: 1.0.0
        paths:
            /api/login_check:
                post:
                    tags:
                        - Token

                    operationId: postCredentialsItem
                    summary: Permet d'obtenir le token JWT pour se logger.
                    requestBody:
                        description: Crée un nouveau token JWT
                        content:
                            application/json:
                                schema:
                                          $ref: '#/components/schemas/Credentials'
                    responses:
                        '200':
                            description: Récupère le token JWT
                            content:
                                application/json:
                                    schema:
                                          $ref: '#/components/schemas/Token'
            /api/product:
                post:
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        name:
                                            type: string
                                        description:
                                            type: string
                                        price:
                                            type: float
                                        image:
                                            type: string
                                        manufacturer:
                                            type: string
                                        length:
                                            type: float
                                        width:
                                            type: float
                                        weight:
                                            type: float
            /api/product/{id}:
                put:
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        name:
                                            type: string
                                        description:
                                            type: string
                                        price:
                                            type: float
                                        image:
                                            type: string
                                        manufacturer:
                                            type: string
                                        length:
                                            type: float
                                        width:
                                            type: float
                                        weight:
                                            type: float
            /api/user/{id}:
                put:
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        company:
                                            type: string
                                        email:
                                            type: string
            /api/user/{id}/customer:
                post:
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                        name:
                                            type: string     
            /api/user/{id}/customer/{id_customer}:
                put:
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        email:
                                            type: string
                                        name:
                                            type: string                                                                        
        components:
            schemas:
                Token:
                    type: object
                    properties:
                        token:
                            type: string
                            readOnly: true
                Credentials:
                    type: object
                    properties:
                        username:
                            type: string
                            default: Boulay
                        password:
                            type: string
                            default: password
            securitySchemes:
                bearerAuth:
                    type: apiKey
                    in: header
                    name: Authorization # or another header name
        security:
            - bearerAuth: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc